name = "KR Biz Tool"
packages = [
    "jinja2",
    "pandas",
    "pyyaml",
    "msoffcrypto-tool",
    "openpyxl",
    "xlrd",
    "xlsxwriter",
    "rich",
    "pygments"
]

[files]
"_templates/order-file-table.html.jinja" = "_templates/order-file-table.html.jinja"
"_templates/order-file-list-item.html.jinja" = "_templates/order-file-list-item.html.jinja"
"_templates/__init__.py" = "_templates/__init__.py"
"_resources/default_krbiz_order_unified_row_names.xlsx" = "_resources/default_krbiz_order_unified_row_names.xlsx"
"_resources/default_krbiz_delivery_format.xlsx" = "_resources/default_krbiz_delivery_format.xlsx"
"merge_order.py" = "merge_order.py"
"order_settings.py" = "order_settings.py"
"order_file_io.py" = "order_file_io.py"
"excel_helpers.py" = "excel_helpers.py"
"delivery_form.py" = "delivery_form.py"
"main.py" = "main.py"
